# Chapter 2: Vectors, matrices and multidimensional arrays

Robert Johansson

Updated source code listings for Numerical Python - A Practical Techniques Approach for Industry (ISBN 978-1-484205-54-9).

Updator: Kee-Youn Yoo

In [2]:
import numpy as np

## The Numpy array object

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int64')

In [9]:
data.nbytes

48

## Data types

In [10]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [11]:
d1=np.array([1, 2, 3], dtype=np.float)

In [12]:
d1.dtype

dtype('float64')

In [13]:
np.array([1, 2, 3], dtype=np.complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j])

### Type casting

In [20]:
data = np.array([1, 2, 3], dtype=np.float)

In [21]:
data.dtype

dtype('float64')

In [22]:
data

array([ 1.,  2.,  3.])

In [16]:
data = np.array(data, dtype=np.int)

In [17]:
data.dtype

dtype('int64')

In [18]:
data

array([1, 2, 3])

*or*

In [23]:
data = np.array([1.6, 2, 3], dtype=np.float)

In [24]:
data.astype(np.int)

array([1, 2, 3])

### Type promotion

In [25]:
d1 = np.array([1, 2, 3], dtype=float)

In [26]:
d2 = np.array([1, 2, 3], dtype=complex)

In [27]:
d1 + d2

array([ 2.+0.j,  4.+0.j,  6.+0.j])

In [28]:
(d1 + d2).dtype

dtype('complex128')

### Type-depending operation

In [29]:
np.sqrt(np.array([-1, 0, 1]))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([ nan,   0.,   1.])

In [30]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([ 0.+1.j,  0.+0.j,  1.+0.j])

### Real and imaginary parts 

In [31]:
data = np.array([1, 2, 3], dtype=complex); data

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [32]:
data.real

array([ 1.,  2.,  3.])

In [33]:
data.imag

array([ 0.,  0.,  0.])

In [34]:
np.real(data)

array([ 1.,  2.,  3.])

In [35]:
np.imag(data)

array([ 0.,  0.,  0.])

### Order of array data in memory

Multidimensional arrays are stored as contiguous data in memory. Consider the case of a two-dimensional array, containing rows and columns: One possible way to store this array as a consecutive sequence of values is to store the rows after each other, and another equally valid approach is to store the columns one after another. The former is called row-major format and the latter is column-major format. Whether to use row-major or column-major is a matter of conventions, and the **row-major format** is used for example in the **C** programming language, and **Fortran** uses the **column-major format**. 

A `NumPy` array can be specified to be stored in row-major format, using the keyword argument `order='C'`, and column-major format, using the keyword argument `order='F'`, when the array is created or reshaped. The default format is *row-major*. 

In general, the `NumPy` array attribute `ndarray.strides` defines exactly how this mapping is done. The `strides` attribute is a tuple of the same length as the number of axes (dimensions) of the array. Each value in `strides` is the factor by which the index for the corresponding axis is multiplied when calculating the *memory offset (in bytes)* for a given index expression.

In [36]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [37]:
data.strides

(12, 4)

In [38]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64, order='F')

In [39]:
data.strides

(8, 16)

## Creating arrays

### Arrays created from lists and other array-like objects

In [40]:
data = np.array([1, 2, 3, 4])

In [41]:
data.ndim

1

In [42]:
data.shape

(4,)

In [43]:
data = np.array([[1, 2], [3, 4]])

In [44]:
data.ndim

2

In [45]:
data.shape

(2, 2)

### Arrays filled with constant values

In [46]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [47]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

---

In [48]:
data = np.ones(4)

In [49]:
data.dtype

dtype('float64')

In [50]:
data = np.ones(4, dtype=np.int64)

In [51]:
data.dtype

dtype('int64')

---

In [52]:
5.4 * np.ones(10)

array([ 5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4])

In [53]:
np.full(10, 5.4) # slightly more efficient

array([ 5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4,  5.4])

---

In [54]:
x1 = np.empty(5); x1.fill(3.0)

In [55]:
x1

array([ 3.,  3.,  3.,  3.,  3.])

### Arrays filled with incremental sequences

In [58]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
np.linspace(0, 10, 11) # generally recommended

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

### Arrays filled with logarithmic sequences 

In [60]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

### Mesh grid arrays

In [61]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

In [62]:
X, Y = np.meshgrid(x, y)

In [63]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [64]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [69]:
Z = (X + Y)**2; Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

### Creating uninitialized arrays

In [71]:
x = np.empty(3, dtype=np.float); x

array([ 1.,  2.,  3.])

### Creating arrays with properties of other arrays

In [72]:
def f(x):    
    y = np.ones_like(x)    # compute with x and y    
    return y

x = np.array([[1, 2, 3], [4, 5, 6]])
y = f(x); y

array([[1, 1, 1],
       [1, 1, 1]])

### Creating matrix arrays

In [73]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [74]:
np.eye(4, k=1)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [75]:
np.eye(4, k=-1)

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [76]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Indexing and slicing

### One-dimensional arrays

In [77]:
a = np.arange(0, 11); a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
a[0]

0

In [79]:
a[-1]

10

In [80]:
a[4]

4

---

In [81]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

---

In [83]:
a[:5]

array([0, 1, 2, 3, 4])

In [84]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [85]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

### Multidimensional arrays

In [86]:
f = lambda m, n: n +10*m

In [87]:
A = np.fromfunction(f, (6, 6), dtype=int); A # please search for numpy.fromfunction at google

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

---

In [88]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [89]:
A[1, :]  # the second raw

array([10, 11, 12, 13, 14, 15])

In [90]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [91]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [92]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [93]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

Subarrays that are extracted from arrays using slice operations are **alternative views** of the same underlying
array data. That is, they are arrays that refer to the same data in memory as the original array, but with a
different `strides` configuration. When elements in a view are assigned new values, the values of the original
array are therefore also updated. For example,

In [94]:
B = A[1:5, 1:5]; B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [95]:
B[:, :] = 0; A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

When **a copy rather than a view** is needed, the view can be copied explicitly by using
the `copy` method of the `ndarray` instance.

In [96]:
C = B[1:3, 1:3].copy(); C

array([[0, 0],
       [0, 0]])

In [97]:
C[:, :] = 1; C

array([[1, 1],
       [1, 1]])

In [98]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and boolean-valued indexing

In [99]:
A = np.linspace(0, 1, 11); A

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [100]:
A[np.array([0, 2, 4])]

array([ 0. ,  0.2,  0.4])

In [101]:
A[[0, 2, 4]]

array([ 0. ,  0.2,  0.4])

---

In [102]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [103]:
A[A > 0.5]

array([ 0.6,  0.7,  0.8,  0.9,  1. ])

Unlike arrays created by using slices, **the arrays returned using fancy indexing and Boolean-valued
indexing are not views**, but rather new independent arrays.

In [104]:
A = np.arange(10)

In [105]:
indices = [2, 4, 6]

In [106]:
B = A[indices]

In [107]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
A[indices] = -1; A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

---

In [109]:
A = np.arange(10)

In [110]:
B = A[A > 5]

In [111]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
A[A > 5] = -1; A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

### Summery

<table>
<tr>
<td><img src="./figs/array_indexing_01.svg"></td>
<td><img src="./figs/array_indexing_02.svg"></td>
<td><img src="./figs/array_indexing_03.svg"></td>
<td><img src="./figs/array_indexing_04.svg"></td>
</tr>
<tr>
<td><img src="./figs/array_indexing_05.svg"></td>
<td><img src="./figs/array_indexing_06.svg"></td>
<td><img src="./figs/array_indexing_07.svg"></td>
<td><img src="./figs/array_indexing_08.svg"></td>
</tr>
<tr>
<td><img src="./figs/array_indexing_09.svg"></td>
<td><img src="./figs/array_indexing_10.svg"></td>
<td><img src="./figs/array_indexing_11.svg"></td>
<td><img src="./figs/array_indexing_12.svg"></td>
</tr>
</table>

## Reshaping and resizing

Reshaping an array does not require modifying the underlying array data; it only changes in how the
data is interpreted, by redefining the array’s `strides` attribute.

In [113]:
data = np.array([[1, 2], [3, 4]])

In [114]:
data1 = np.reshape(data, (1, 4)); data1

array([[1, 2, 3, 4]])

In [115]:
data1[0, 1] = -1; data

array([[ 1, -1],
       [ 3,  4]])

In [116]:
data2 = data.reshape(4); data2

array([ 1, -1,  3,  4])

In [117]:
data2[1] = -2; data

array([[ 1, -2],
       [ 3,  4]])

---

In [118]:
data = np.array([[1, 2], [3, 4]])

In [119]:
data1 = np.ravel(data); data1

array([1, 2, 3, 4])

In [120]:
data1[0] = -1; data

array([[-1,  2],
       [ 3,  4]])

The `ndarray` method `flatten` perform the same function, but
returns a **copy** instead of a view.

In [121]:
data2 = data.flatten(); data2

array([-1,  2,  3,  4])

In [122]:
data2[0] = -2; data

array([[-1,  2],
       [ 3,  4]])

---

In [3]:
data = np.arange(0, 5); data.shape

(5,)

In [124]:
column = data[:, np.newaxis]; column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [127]:
column.shape

(5, 1)

In [125]:
row = data[np.newaxis, :]; row

array([[0, 1, 2, 3, 4]])

In [128]:
row.shape

(1, 5)

In [129]:
row[0, 0] = -1; data

array([-1,  1,  2,  3,  4])

In [130]:
np.expand_dims(data, axis=1)

array([[-1],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [131]:
np.expand_dims(data, axis=0)

array([[-1,  1,  2,  3,  4]])

---

In [132]:
data = np.arange(5); data

array([0, 1, 2, 3, 4])

In [133]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [134]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [135]:
data = data[:, np.newaxis]; data.shape

(5, 1)

In [136]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [137]:
data1 = np.array([[1, 2], [3, 4]])

In [138]:
data2 = np.array([[5, 6]])

In [139]:
np.concatenate((data1, data2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [140]:
np.concatenate((data1, data2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Vectorized expressions

### Arithmetic operations

In [141]:
x = np.array([[1, 2], [3, 4]])

In [142]:
y = np.array([[5, 6], [7, 8]])

In [143]:
x + y

array([[ 6,  8],
       [10, 12]])

In [144]:
y - x

array([[4, 4],
       [4, 4]])

In [145]:
x * y

array([[ 5, 12],
       [21, 32]])

In [146]:
y / x

array([[ 5.        ,  3.        ],
       [ 2.33333333,  2.        ]])

---

In [147]:
x * 2

array([[2, 4],
       [6, 8]])

In [148]:
2**x

array([[ 2,  4],
       [ 8, 16]])

In [149]:
y / 2

array([[ 2.5,  3. ],
       [ 3.5,  4. ]])

In [150]:
(y / 2).dtype

dtype('float64')

---

<table>
<tr>
<td><img src="./figs/array_broadcasting_1.svg"></td>
</tr>
<tr>
<td><img src="./figs/array_broadcasting_2.svg"></td>
</tr>
<tr>
</table>

In [151]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([1, 2, 3, 4])
x / y

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [152]:
z = np.array([[2, 4]]); z.shape

(1, 2)

In [153]:
x / z

array([[ 0.5,  0.5],
       [ 1.5,  1. ]])

In [154]:
zz = np.vstack((z, z)); zz

array([[2, 4],
       [2, 4]])

In [155]:
x / zz

array([[ 0.5,  0.5],
       [ 1.5,  1. ]])

---

In [156]:
z = np.array([[2], [4]]); z.shape

(2, 1)

In [157]:
x / z

array([[ 0.5 ,  1.  ],
       [ 0.75,  1.  ]])

In [158]:
zz = np.concatenate([z, z], axis=1); zz

array([[2, 2],
       [4, 4]])

In [159]:
x / zz

array([[ 0.5 ,  1.  ],
       [ 0.75,  1.  ]])

---

In [160]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
x = x + y  # x is reassigned to a new array

In [161]:
x += y  # the values of array x are updated in place

### Elementwise functions

In [162]:
x = np.linspace(-1, 1, 11); x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [163]:
y = np.sin(np.pi * x)

In [164]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [165]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [166]:
np.sin(x)**2 + np.cos(x)**2

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

---

In [167]:
def heaviside(x):
    return 1 if x > 0 else 0

In [168]:
heaviside(-1)

0

In [169]:
heaviside(1.5)

1

In [170]:
x = np.linspace(-5, 5, 11)
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [171]:
heaviside = np.vectorize(heaviside)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [173]:
def heaviside(x):  # much better way
    return 1 * (x > 0)

heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

### Aggregate functions

In [174]:
data = np.random.normal(size=(15, 15))

In [175]:
np.mean(data)

-0.047446991943741482

In [176]:
data.mean()

-0.047446991943741482

---

In [177]:
data = np.random.normal(size=(5, 10, 15))

In [178]:
data.sum(axis=0).shape

(10, 15)

In [179]:
data.sum(axis=(0, 2)).shape

(10,)

In [180]:
data.sum()

-33.002072830794575

---

In [181]:
data = np.arange(1, 10).reshape(3, 3); data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
data.sum()

45

In [183]:
data.sum(axis=0)

array([12, 15, 18])

In [184]:
data.sum(axis=1)

array([ 6, 15, 24])

<table>
<tr>
<td><img src="./figs/array_aggregation_1.svg"></td>
<td><img src="./figs/array_aggregation_2.svg"></td>
<td><img src="./figs/array_aggregation_3.svg"></td>
</tr>
</table>

### Boolean arrays and conditional expressions

In [185]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [186]:
a < b

array([ True,  True, False, False], dtype=bool)

---

In [187]:
np.all(a < b)

False

In [188]:
np.any(a < b)

True

In [189]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding elements in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elements in b")
else:
    print("All elements in b are smaller than their corresponding elements in a")

Some elements in a are smaller than their corresponding elements in b


---

In [190]:
x = np.array([-2, -1, 0, 1, 2])

In [191]:
x > 0

array([False, False, False,  True,  True], dtype=bool)

In [192]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [193]:
x * (x > 0)

array([0, 0, 0, 1, 2])

---

In [194]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

#   return height *np.logical_and(x >= position, x <= (position + width))                                       

In [195]:
x = np.linspace(-5, 5, 11)

In [196]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [197]:
pulse(x, position=1, height=2, width=2)

array([0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0])

---

In [198]:
x = np.linspace(-4, 4, 9)

In [199]:
np.where(x < 0, x**2, x**3)

array([ 16.,   9.,   4.,   1.,   0.,   1.,   8.,  27.,  64.])

In [200]:
np.select([x < -1, x < 2, x>= 2], [x**2, x**3, x**4])

array([  16.,    9.,    4.,   -1.,    0.,    1.,   16.,   81.,  256.])

In [201]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

array([  16.,    9.,    4.,   -1.,    0.,    1.,   16.,   81.,  256.])

---

In [202]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8]),)

In [203]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [204]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

### Set operations

In [211]:
a = np.unique([1, 2, 3, 3]); a

array([1, 2, 3])

In [212]:
b = np.unique([2, 3, 4, 4, 5, 6, 5]); b

array([2, 3, 4, 5, 6])

In [207]:
np.in1d(a, b)

array([False,  True,  True], dtype=bool)

In [208]:
1 in a

True

In [209]:
1 in b

False

In [213]:
np.all(np.in1d(a, b))  # to test if a is a subset of b

False

---

In [214]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [215]:
np.intersect1d(a, b)

array([2, 3])

In [216]:
np.setdiff1d(a, b)

array([1])

In [217]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on arrays

In [218]:
data = np.arange(9).reshape(3, 3); data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [219]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

---

In [221]:
data = np.random.randn(1, 2, 3, 4, 5); data

array([[[[[ 0.52522058,  0.30487447,  0.33033303,  1.6636482 , -0.65685269],
          [-0.05836145, -1.08041297,  0.41411719, -0.58837203,  0.68611236],
          [ 1.56805151,  0.99316017, -0.81372835, -0.98188659, -0.0779225 ],
          [ 0.20738397, -0.8895817 , -1.01184227,  0.27011727, -1.5463157 ]],

         [[-0.66382495,  0.85369158, -1.42192986, -0.84723485, -0.16403326],
          [ 1.07487741,  0.71054967,  1.78294278, -1.13686014,  0.29536235],
          [-0.48384711, -0.20404314, -1.97902526,  1.14544116,  0.68355549],
          [ 1.41720214,  0.6650169 ,  1.05325623, -0.21373417,  0.67336075]],

         [[-0.55689068, -0.61983767,  0.02208619,  1.26694322, -1.67798283],
          [ 1.68193285,  1.17193808,  0.45128147,  0.93117095, -0.40398368],
          [-0.22122311,  0.47041666, -0.88089735,  0.98688812, -1.75905154],
          [-0.33947057, -0.18393247,  0.14722366,  1.14329726, -0.95674428]]],


        [[[-1.06597598, -0.04835412,  0.50029649,  1.81906169,  1.14

In [222]:
data.shape

(1, 2, 3, 4, 5)

In [223]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

In [224]:
A = np.arange(1, 7).reshape(2, 3); A

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
B = np.arange(1, 7).reshape(3, 2); B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [226]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [227]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

---

In [228]:
A = np.arange(9).reshape(3, 3); A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [229]:
x = np.arange(3); x

array([0, 1, 2])

In [230]:
np.dot(A, x)

array([ 5, 14, 23])

In [231]:
A.dot(x)

array([ 5, 14, 23])

---

In [232]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

In [233]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [234]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

---

In [235]:
A1 = np.matrix(A)
B1 = np.matrix(B)

In [236]:
Ap = B1 * A1 * B1.I

In [237]:
A2 = np.asmatrix(A)
B2 = np.asmatrix(B)

In [238]:
Ap = B2 * A2 * B2.I

In [239]:
Ap = np.asarray(Ap)

---

In [240]:
np.inner(x, x)

5

In [241]:
np.dot(x, x)

5

In [242]:
y = x[:, np.newaxis]; y

array([[0],
       [1],
       [2]])

In [243]:
np.dot(y.T, y)

array([[5]])

---

In [244]:
x = np.array([1, 2, 3])

In [245]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [246]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [247]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [248]:
np.kron(np.ones((2, 2)), np.identity(2))

array([[ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.]])

In [249]:
np.kron(np.identity(2), np.ones((2, 2)))

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  1.,  1.]])

---

In [250]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [251]:
np.einsum("n,n", x, y)

70

In [252]:
np.inner(x, y)

70

In [253]:
A = np.arange(9).reshape(3, 3)
B = A.T

In [254]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [255]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

## Versions

In [256]:
%reload_ext version_information
%version_information numpy

Software versions
Python 3.6.1 64bit [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
IPython 5.3.0
OS Linux 4.9.41 moby x86_64 with debian 8.5
numpy 1.13.1
Fri Sep 22 13:55:23 2017 UTC