# Chapter 2: Vectors, matrices and multidimensional arrays

Creator: Robert Johansson, Updator: Kee-Youn Yoo

Updated source code listings for Numerical Python - A Practical Techniques Approach for Industry (ISBN 978-1-484205-54-9).

In [ ]:
import numpy as np

## The Numpy array object

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
type(data)

In [ ]:
data

In [ ]:
data.ndim

In [ ]:
data.shape

In [ ]:
data.size

In [ ]:
data.dtype

In [ ]:
data.nbytes

## Data types

In [ ]:
np.array([1, 2, 3], dtype=np.int)

In [11]:
d1=np.array([1, 2, 3], dtype=np.float)

In [12]:
d1.dtype

dtype('float64')

In [13]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### Type casting

In [14]:
data = np.array([1, 2, 3], dtype=np.float)

In [15]:
data.dtype

dtype('float64')

In [16]:
data

array([1., 2., 3.])

In [17]:
data = np.array(data, dtype=np.int)

In [18]:
data.dtype

dtype('int32')

In [19]:
data

array([1, 2, 3])

*or*

In [20]:
data = np.array([1.6, 2, 3], dtype=np.float)

In [21]:
data.astype(np.int)

array([1, 2, 3])

### Type promotion

In [22]:
d1 = np.array([1, 2, 3], dtype=float)

In [23]:
d2 = np.array([1, 2, 3], dtype=complex)

In [24]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [25]:
(d1 + d2).dtype

dtype('complex128')

### Type-depending operation

In [26]:
np.sqrt(np.array([-1, 0, 1]))

C:\Users\jesuskyr\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [27]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### Real and imaginary parts 

In [28]:
data = np.array([1, 2, 3], dtype=complex); data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [29]:
data.real

array([1., 2., 3.])

In [30]:
data.imag

array([0., 0., 0.])

In [31]:
np.real(data)

array([1., 2., 3.])

In [32]:
np.imag(data)

array([0., 0., 0.])

### Order of array data in memory

Multidimensional arrays are stored as contiguous data in memory. Consider the case of a two-dimensional array, containing rows and columns: One possible way to store this array as a consecutive sequence of values is to store the rows after each other, and another equally valid approach is to store the columns one after another. The former is called row-major format and the latter is column-major format. Whether to use row-major or column-major is a matter of conventions, and the **row-major format** is used for example in the **C** programming language, and **Fortran** uses the **column-major format**. 

A `NumPy` array can be specified to be stored in row-major format, using the keyword argument `order='C'`, and column-major format, using the keyword argument `order='F'`, when the array is created or reshaped. The default format is *row-major*. 

In general, the `NumPy` array attribute `ndarray.strides` defines exactly how this mapping is done. The `strides` attribute is a tuple of the same length as the number of axes (dimensions) of the array. Each value in `strides` is the factor by which the index for the corresponding axis is multiplied when calculating the *memory offset (in bytes)* for a given index expression.

In [33]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [34]:
data.strides

(12, 4)

In [35]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64, order='F')

In [36]:
data.strides

(8, 16)

## Creating arrays

### Arrays created from lists and other array-like objects

In [37]:
data = np.array([1, 2, 3, 4])

In [38]:
data.ndim

1

In [39]:
data.shape

(4,)

In [40]:
data = np.array([[1, 2], [3, 4]])

In [41]:
data.ndim

2

In [42]:
data.shape

(2, 2)

### Arrays filled with constant values

In [43]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

---

In [45]:
data = np.ones(4)

In [46]:
data.dtype

dtype('float64')

In [47]:
data = np.ones(4, dtype=np.int64)

In [48]:
data.dtype

dtype('int64')

---

In [49]:
5.4 * np.ones(10)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [50]:
np.full(10, 5.4) # slightly more efficient

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

---

In [51]:
x1 = np.empty(5); x1.fill(3.0)

In [52]:
x1

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [53]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
np.linspace(0, 10, 11) # generally recommended

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences 

In [55]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh grid arrays

In [56]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

In [57]:
X, Y = np.meshgrid(x, y)

In [58]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [59]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [60]:
Z = (X + Y)**2; Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

### Creating uninitialized arrays

In [61]:
x = np.empty(3, dtype=np.float); x

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313])

### Creating arrays with properties of other arrays

In [62]:
def f(x):    
    y = np.ones_like(x)    # compute with x and y    
    return y

x = np.array([[1, 2, 3], [4, 5, 6]])
y = f(x); y

array([[1, 1, 1],
       [1, 1, 1]])

### Creating matrix arrays

In [63]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [65]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Indexing and slicing

### One-dimensional arrays

In [67]:
a = np.arange(0, 11); a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a[0]

0

In [69]:
a[-1]

10

In [70]:
a[4]

4

---

In [71]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

---

In [73]:
a[:5]

array([0, 1, 2, 3, 4])

In [74]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [75]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

### Multidimensional arrays

In [76]:
f = lambda m, n: n +10*m

In [77]:
A = np.fromfunction(f, (6, 6), dtype=int); A # please search for numpy.fromfunction at google

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

---

In [78]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [79]:
A[1, :]  # the second raw

array([10, 11, 12, 13, 14, 15])

In [80]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [81]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [82]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [83]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

Subarrays that are extracted from arrays using slice operations are **alternative views** of the same underlying
array data. That is, they are arrays that refer to the same data in memory as the original array, but with a
different `strides` configuration. When elements in a view are assigned new values, the values of the original
array are therefore also updated. For example,

In [84]:
B = A[1:5, 1:5]; B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [85]:
B[:, :] = 0; A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

When **a copy rather than a view** is needed, the view can be copied explicitly by using
the `copy` method of the `ndarray` instance.

In [86]:
C = B[1:3, 1:3].copy(); C

array([[0, 0],
       [0, 0]])

In [87]:
C[:, :] = 1; C

array([[1, 1],
       [1, 1]])

In [88]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and boolean-valued indexing

In [89]:
A = np.linspace(0, 1, 11); A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [90]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [91]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

---

In [92]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [93]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

Unlike arrays created by using slices, **the arrays returned using fancy indexing and Boolean-valued
indexing are not views**, but rather new independent arrays.

In [94]:
A = np.arange(10)

In [95]:
indices = [2, 4, 6]

In [96]:
B = A[indices]

In [97]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
A[indices] = -1; A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

---

In [99]:
A = np.arange(10)

In [100]:
B = A[A > 5]

In [101]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
A[A > 5] = -1; A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

### Summery

<table>
<tr>
<td><img src="./figs/array_indexing_01.png"></td>
<td><img src="./figs/array_indexing_02.png"></td>
<td><img src="./figs/array_indexing_03.png"></td>
<td><img src="./figs/array_indexing_04.png"></td>
</tr>
<tr>
<td><img src="./figs/array_indexing_05.png"></td>
<td><img src="./figs/array_indexing_06.png"></td>
<td><img src="./figs/array_indexing_07.png"></td>
<td><img src="./figs/array_indexing_08.png"></td>
</tr>
<tr>
<td><img src="./figs/array_indexing_09.png"></td>
<td><img src="./figs/array_indexing_10.png"></td>
<td><img src="./figs/array_indexing_11.png"></td>
<td><img src="./figs/array_indexing_12.png"></td>
</tr>
</table>

## Reshaping and resizing

Reshaping an array does not require modifying the underlying array data; it only changes in how the
data is interpreted, by redefining the array’s `strides` attribute.

In [103]:
data = np.array([[1, 2], [3, 4]])

In [104]:
data1 = np.reshape(data, (1, 4)); data1

array([[1, 2, 3, 4]])

In [105]:
data1[0, 1] = -1; data

array([[ 1, -1],
       [ 3,  4]])

In [106]:
data2 = data.reshape(4); data2

array([ 1, -1,  3,  4])

In [107]:
data2[1] = -2; data

array([[ 1, -2],
       [ 3,  4]])

---

In [108]:
data = np.array([[1, 2], [3, 4]])

In [109]:
data1 = np.ravel(data); data1

array([1, 2, 3, 4])

In [110]:
data1[0] = -1; data

array([[-1,  2],
       [ 3,  4]])

The `ndarray` method `flatten` perform the same function, but
returns a **copy** instead of a view.

In [111]:
data2 = data.flatten(); data2

array([-1,  2,  3,  4])

In [112]:
data2[0] = -2; data

array([[-1,  2],
       [ 3,  4]])

---

In [113]:
data = np.arange(0, 5); data.shape

(5,)

In [114]:
column = data[:, np.newaxis]; column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [115]:
column.shape

(5, 1)

In [116]:
row = data[np.newaxis, :]; row

array([[0, 1, 2, 3, 4]])

In [117]:
row.shape

(1, 5)

In [118]:
row[0, 0] = -1; data

array([-1,  1,  2,  3,  4])

In [119]:
np.expand_dims(data, axis=1)

array([[-1],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [120]:
np.expand_dims(data, axis=0)

array([[-1,  1,  2,  3,  4]])

---

In [121]:
data = np.arange(5); data

array([0, 1, 2, 3, 4])

In [122]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [123]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [124]:
data = data[:, np.newaxis]; data.shape

(5, 1)

In [125]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [126]:
data1 = np.array([[1, 2], [3, 4]])

In [127]:
data2 = np.array([[5, 6]])

In [128]:
np.concatenate((data1, data2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
np.concatenate((data1, data2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Vectorized expressions

### Arithmetic operations

In [130]:
x = np.array([[1, 2], [3, 4]])

In [131]:
y = np.array([[5, 6], [7, 8]])

In [132]:
x + y

array([[ 6,  8],
       [10, 12]])

In [133]:
y - x

array([[4, 4],
       [4, 4]])

In [134]:
x * y

array([[ 5, 12],
       [21, 32]])

In [135]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

---

In [136]:
x * 2

array([[2, 4],
       [6, 8]])

In [137]:
2**x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [138]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [139]:
(y / 2).dtype

dtype('float64')

---

<table>
<tr>
<td><img src="./figs/array_broadcasting_1.png"></td>
</tr>
<tr>
<td><img src="./figs/array_broadcasting_2.png"></td>
</tr>
<tr>
</table>

In [140]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([1, 2, 3, 4])
x / y

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [141]:
z = np.array([[2, 4]]); z.shape

(1, 2)

In [142]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [143]:
zz = np.vstack((z, z)); zz

array([[2, 4],
       [2, 4]])

In [144]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

---

In [145]:
z = np.array([[2], [4]]); z.shape

(2, 1)

In [146]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [147]:
zz = np.concatenate([z, z], axis=1); zz

array([[2, 2],
       [4, 4]])

In [148]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

---

In [149]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
x = x + y  # x is reassigned to a new array

In [150]:
x += y  # the values of array x are updated in place

### Elementwise functions

In [151]:
x = np.linspace(-1, 1, 11); x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [152]:
y = np.sin(np.pi * x)

In [153]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [154]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [155]:
np.sin(x)**2 + np.cos(x)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

---

In [156]:
def heaviside(x):
    return 1 if x > 0 else 0

In [157]:
heaviside(-1)

0

In [158]:
heaviside(1.5)

1

In [159]:
x = np.linspace(-5, 5, 11)
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [160]:
heaviside = np.vectorize(heaviside)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [161]:
def heaviside(x):  # much better way
    return 1 * (x > 0)

heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

### Aggregate functions

In [162]:
data = np.random.normal(size=(15, 15))

In [163]:
np.mean(data)

0.03928209218627804

In [164]:
data.mean()

0.03928209218627804

---

In [165]:
data = np.random.normal(size=(5, 10, 15))

In [166]:
data.sum(axis=0).shape

(10, 15)

In [167]:
data.sum(axis=(0, 2)).shape

(10,)

In [168]:
data.sum()

5.622773122656627

---

In [169]:
data = np.arange(1, 10).reshape(3, 3); data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
data.sum()

45

In [171]:
data.sum(axis=0)

array([12, 15, 18])

In [172]:
data.sum(axis=1)

array([ 6, 15, 24])

<table>
<tr>
<td><img src="./figs/array_aggregation_1.png"></td>
<td><img src="./figs/array_aggregation_2.png"></td>
<td><img src="./figs/array_aggregation_3.png"></td>
</tr>
</table>

### Boolean arrays and conditional expressions

In [173]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [174]:
a < b

array([ True,  True, False, False])

---

In [175]:
np.all(a < b)

False

In [176]:
np.any(a < b)

True

In [177]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding elements in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elements in b")
else:
    print("All elements in b are smaller than their corresponding elements in a")

Some elements in a are smaller than their corresponding elements in b


---

In [178]:
x = np.array([-2, -1, 0, 1, 2])

In [179]:
x > 0

array([False, False, False,  True,  True])

In [180]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [181]:
x * (x > 0)

array([0, 0, 0, 1, 2])

---

In [182]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

#   return height *np.logical_and(x >= position, x <= (position + width))                                       

In [183]:
x = np.linspace(-5, 5, 11)

In [184]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [185]:
pulse(x, position=1, height=2, width=2)

array([0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0])

---

In [186]:
x = np.linspace(-4, 4, 9)

In [187]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [188]:
np.select([x < -1, x < 2, x>= 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [189]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

---

In [190]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [191]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [192]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

### Set operations

In [193]:
a = np.unique([1, 2, 3, 3]); a

array([1, 2, 3])

In [194]:
b = np.unique([2, 3, 4, 4, 5, 6, 5]); b

array([2, 3, 4, 5, 6])

In [195]:
np.in1d(a, b)

array([False,  True,  True])

In [196]:
1 in a

True

In [197]:
1 in b

False

In [198]:
np.all(np.in1d(a, b))  # to test if a is a subset of b

False

---

In [199]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [200]:
np.intersect1d(a, b)

array([2, 3])

In [201]:
np.setdiff1d(a, b)

array([1])

In [202]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on arrays

In [203]:
data = np.arange(9).reshape(3, 3); data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [204]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

---

In [205]:
data = np.random.randn(1, 2, 3, 4, 5); data

array([[[[[ 1.78766363,  1.39326873,  0.15243713,  0.36755828,
           -1.17343339],
          [-0.40750796,  0.23366227,  0.74139711, -1.27283973,
           -0.19157928],
          [-0.96695536,  0.35636917, -1.00531104, -0.07550398,
           -1.37041801],
          [-1.13942995, -0.60434373, -0.11700463, -0.87278407,
           -0.96517891]],

         [[-0.4717228 ,  0.29545612, -0.58011561,  0.58987121,
           -0.6734019 ],
          [-1.32161227,  2.22840191,  0.51346815,  0.93386518,
            0.66934087],
          [-0.27998729,  0.06180266, -0.33483304, -1.93960411,
            0.06526783],
          [-0.7283601 , -0.48833509,  1.91457626, -0.51737345,
            0.60718968]],

         [[-1.07371696, -0.10827465, -0.16106956, -1.95194812,
           -1.51985573],
          [-1.5391204 ,  0.40248622, -1.22073064,  0.93283576,
            0.97925073],
          [ 0.80922108, -0.44318956, -0.1016028 ,  0.43031119,
            0.83122027],
          [ 0.10154689,  1.6

In [206]:
data.shape

(1, 2, 3, 4, 5)

In [207]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

In [208]:
A = np.arange(1, 7).reshape(2, 3); A

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
B = np.arange(1, 7).reshape(3, 2); B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [210]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [211]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

---

In [212]:
A = np.arange(9).reshape(3, 3); A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [213]:
x = np.arange(3); x

array([0, 1, 2])

In [214]:
np.dot(A, x)

array([ 5, 14, 23])

In [215]:
A.dot(x)

array([ 5, 14, 23])

---

In [216]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

In [217]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [218]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

---

In [219]:
A1 = np.matrix(A)
B1 = np.matrix(B)

In [220]:
Ap = B1 * A1 * B1.I

In [221]:
A2 = np.asmatrix(A)
B2 = np.asmatrix(B)

In [222]:
Ap = B2 * A2 * B2.I

In [223]:
Ap = np.asarray(Ap)

---

In [224]:
np.inner(x, x)

5

In [225]:
np.dot(x, x)

5

In [226]:
y = x[:, np.newaxis]; y

array([[0],
       [1],
       [2]])

In [227]:
np.dot(y.T, y)

array([[5]])

---

In [228]:
x = np.array([1, 2, 3])

In [229]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [230]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [231]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [232]:
np.kron(np.ones((2, 2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [233]:
np.kron(np.identity(2), np.ones((2, 2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

---

In [234]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [235]:
np.einsum("n,n", x, y)

70

In [236]:
np.inner(x, y)

70

In [237]:
A = np.arange(9).reshape(3, 3)
B = A.T

In [238]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [239]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

## Versions

In [240]:
print("numpy: ", np.__version__)

numpy:  1.16.5
